#!/usr/bin/env python3
"""Dump the SDK's own capability spec for a device to docs/device-capabilities.md.

This is the *static* counterpart to what the app probes at runtime.
Where the two disagree, believe the watch.
"""
import json, os, sys

device = sys.argv[1] if len(sys.argv) > 1 else "fr745"
root = os.path.expanduser(f"~/.Garmin/ConnectIQ/Devices/{device}")
if not os.path.isdir(root):
    sys.exit(f"device '{device}' not installed. Run: connect-iq-sdk-manager device download -d {device}")

with open(os.path.join(root, "compiler.json"), encoding="utf-8") as fh:
    c = json.load(fh)

L = [f"# {device} — capabilities per the Connect IQ SDK\n",
     "Generated by `tools/dump-device-caps.py`. Static SDK spec; the app's",
     "runtime probe is the authority where the two disagree.\n",
     "## Display\n"]

res = c.get("resolution", {})
L += [f"- **resolution**: {res.get('width')}x{res.get('height')}",
      f"- **family**: {c.get('deviceFamily')}",
      f"- **panel**: {c.get('displayType')} ({c.get('bitsPerPixel')} bpp)",
      f"- **palette**: {len(c.get('palette', {}).get('colors', []))} colors",
      f"- **alpha blending**: {c.get('alphaBlendingSupport')}",
      f"- **screen rotation**: {c.get('screenRotationSupport')}"]

li = c.get("launcherIcon", {})
if li:
    L.append(f"- **launcher icon**: {li.get('width')}x{li.get('height')}")
L.append("")

L.append("## Memory limits per app type\n")
L.append("| app type | memory |")
L.append("|---|---|")
for a in sorted(c.get("appTypes", []), key=lambda a: -a.get("memoryLimit", 0)):
    kb = a.get("memoryLimit", 0) / 1024
    L.append(f"| {a.get('type')} | {kb:,.0f} KB |")
L.append("")

L.append("## Part numbers\n")
for p in c.get("partNumbers", []):
    langs = [l.get("code", "?") for l in p.get("languages", [])]
    L += [f"### {p.get('number')}\n",
          f"- **Connect IQ**: {p.get('connectIQVersion')}",
          f"- **firmware**: {p.get('firmwareVersion')}",
          f"- **languages** ({len(langs)}): {', '.join(langs)}", ""]

L.append(f"- **device group**: {c.get('deviceGroup')}")

os.makedirs("docs", exist_ok=True)
out = "\n".join(L) + "\n"
with open("docs/device-capabilities.md", "w", encoding="utf-8") as fh:
    fh.write(out)
print(out)
